steps:
  - uses: actions/checkout@v4
  - uses: sarisia/actions-readme-feed@v1
    with:
      url: 'https://qiita.com/clairdeluna_eve/feed'
      file: 'README.md'
  - uses: sarisia/actions-commit@master
